# Generated by Django 2.2 on 2019-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('★☆☆☆☆', '별 한개'), ('★★☆☆☆', '별 두개'), ('★★★☆☆', '별 세개'), ('★★★★☆', '별 네개'), ('★★★★★', '별 다섯개')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
